# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 870)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoWidget = QtWidgets.QWidget(self.centralwidget)
        self.logoWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.logoWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.logoWidget.setStyleSheet("background-color:rgb(0, 170, 255);")
        self.logoWidget.setObjectName("logoWidget")
        self.logolbl = QtWidgets.QLabel(self.logoWidget)
        self.logolbl.setGeometry(QtCore.QRect(1090, 5, 100, 70))
        self.logolbl.setStyleSheet("")
        self.logolbl.setText("")
        self.logolbl.setPixmap(QtGui.QPixmap("../../../../deepmedi_GUI/icons/deepmedi-logo_white_cut.png"))
        self.logolbl.setAlignment(QtCore.Qt.AlignCenter)
        self.logolbl.setObjectName("logolbl")
        self.verticalLayout.addWidget(self.logoWidget)
        self.content_layout = QtWidgets.QWidget(self.centralwidget)
        self.content_layout.setObjectName("content_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content_layout)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.right_layout = QtWidgets.QWidget(self.content_layout)
        self.right_layout.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.right_layout.setObjectName("right_layout")
        self.lblDisplay = QtWidgets.QFrame(self.right_layout)
        self.lblDisplay.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.lblDisplay.setMinimumSize(QtCore.QSize(640, 480))
        self.lblDisplay.setMaximumSize(QtCore.QSize(640, 480))
        self.lblDisplay.setStyleSheet("QFrame {\n"
"    background-color: rgb(85, 0, 127);\n"
"    border-radius: 10;\n"
"}")
        self.lblDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblDisplay.setObjectName("lblDisplay")
        self.btnStart = QtWidgets.QPushButton(self.lblDisplay)
        self.btnStart.setGeometry(QtCore.QRect(10, 420, 51, 51))
        self.btnStart.setObjectName("btnStart")
        self.btnPause = QtWidgets.QPushButton(self.lblDisplay)
        self.btnPause.setGeometry(QtCore.QRect(60, 420, 51, 51))
        self.btnPause.setObjectName("btnPause")
        self.btnStop = QtWidgets.QPushButton(self.lblDisplay)
        self.btnStop.setGeometry(QtCore.QRect(110, 420, 51, 51))
        self.btnStop.setObjectName("btnStop")
        self.horizontalSlider = QtWidgets.QSlider(self.lblDisplay)
        self.horizontalSlider.setGeometry(QtCore.QRect(175, 435, 451, 22))
        self.horizontalSlider.setStyleSheet("background-color: transparent;")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lblclock = QtWidgets.QLabel(self.lblDisplay)
        self.lblclock.setGeometry(QtCore.QRect(575, 456, 61, 21))
        self.lblclock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblclock.setObjectName("lblclock")
        self.groupBox_1 = QtWidgets.QGroupBox(self.right_layout)
        self.groupBox_1.setGeometry(QtCore.QRect(20, 520, 301, 48))
        self.groupBox_1.setStyleSheet("border-line:rgb(0, 0, 127);")
        self.groupBox_1.setObjectName("groupBox_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.camera0_checked = QtWidgets.QRadioButton(self.groupBox_1)
        self.camera0_checked.setObjectName("camera0_checked")
        self.horizontalLayout_2.addWidget(self.camera0_checked)
        self.camera1_checked = QtWidgets.QRadioButton(self.groupBox_1)
        self.camera1_checked.setObjectName("camera1_checked")
        self.horizontalLayout_2.addWidget(self.camera1_checked)
        self.video_checked = QtWidgets.QRadioButton(self.groupBox_1)
        self.video_checked.setObjectName("video_checked")
        self.horizontalLayout_2.addWidget(self.video_checked)
        self.groupBox_2 = QtWidgets.QGroupBox(self.right_layout)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 580, 301, 55))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnOpen = QtWidgets.QPushButton(self.groupBox_2)
        self.btnOpen.setGeometry(QtCore.QRect(10, 21, 61, 23))
        self.btnOpen.setObjectName("btnOpen")
        self.video_auto = QtWidgets.QRadioButton(self.groupBox_2)
        self.video_auto.setGeometry(QtCore.QRect(106, 25, 51, 16))
        self.video_auto.setObjectName("video_auto")
        self.video_manual = QtWidgets.QRadioButton(self.groupBox_2)
        self.video_manual.setGeometry(QtCore.QRect(201, 25, 51, 16))
        self.video_manual.setObjectName("video_manual")
        self.results_box = QtWidgets.QWidget(self.right_layout)
        self.results_box.setGeometry(QtCore.QRect(350, 520, 311, 241))
        self.results_box.setStyleSheet("background-color: rgb(202, 230, 255);\n"
"border-radius: 10;")
        self.results_box.setObjectName("results_box")
        self.gridLayout = QtWidgets.QGridLayout(self.results_box)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.results_box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.results_box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.results_box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.results_box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.right_layout)
        self.pushButton.setGeometry(QtCore.QRect(100, 680, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.realtime_graph_layer = QtWidgets.QWidget(self.right_layout)
        self.realtime_graph_layer.setGeometry(QtCore.QRect(690, 410, 501, 371))
        self.realtime_graph_layer.setStyleSheet("background-color: rgb(202, 230, 255);\n"
"border-radius: 10;")
        self.realtime_graph_layer.setObjectName("realtime_graph_layer")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.realtime_graph_layer)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 481, 351))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.realtime_graph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.realtime_graph.setContentsMargins(0, 0, 0, 0)
        self.realtime_graph.setSpacing(0)
        self.realtime_graph.setObjectName("realtime_graph")
        self.detail_layer = QtWidgets.QWidget(self.right_layout)
        self.detail_layer.setGeometry(QtCore.QRect(690, 20, 501, 371))
        self.detail_layer.setStyleSheet("background-color: rgb(202, 230, 255);\n"
"border-radius: 10;")
        self.detail_layer.setObjectName("detail_layer")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.detail_layer)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 481, 351))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.detail_graph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.detail_graph.setContentsMargins(0, 0, 0, 0)
        self.detail_graph.setSpacing(0)
        self.detail_graph.setObjectName("detail_graph")
        self.horizontalLayout.addWidget(self.right_layout)
        self.verticalLayout.addWidget(self.content_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStart.setText(_translate("MainWindow", "시작"))
        self.btnPause.setText(_translate("MainWindow", "멈춤"))
        self.btnStop.setText(_translate("MainWindow", "정지"))
        self.lblclock.setText(_translate("MainWindow", "Time"))
        self.groupBox_1.setTitle(_translate("MainWindow", "소스를 선택하세요."))
        self.camera0_checked.setText(_translate("MainWindow", "내장카메라"))
        self.camera1_checked.setText(_translate("MainWindow", "외장카메라"))
        self.video_checked.setText(_translate("MainWindow", "비디오"))
        self.groupBox_2.setTitle(_translate("MainWindow", "파일을 선택하세요.(비디오 선택시 활성화 됩니다.)"))
        self.btnOpen.setText(_translate("MainWindow", "Open"))
        self.video_auto.setText(_translate("MainWindow", "자동"))
        self.video_manual.setText(_translate("MainWindow", "수동"))
        self.label_2.setText(_translate("MainWindow", "Repiration Rate"))
        self.label_3.setText(_translate("MainWindow", "True/False"))
        self.label_4.setText(_translate("MainWindow", "BP"))
        self.label.setText(_translate("MainWindow", "HR"))
        self.pushButton.setText(_translate("MainWindow", "저장하고 결과값 보기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

